// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortenerApp.Data;

#nullable disable

namespace URLShortenerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702123128_DatabaseCreation")]
    partial class DatabaseCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URLShortenerApp.Data.Models.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Record identifier");

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime2")
                        .HasComment("URL access date");

                    b.Property<Guid>("URLId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("URL record identifier");

                    b.Property<string>("UserIPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasComment("User IP adress");

                    b.HasKey("Id");

                    b.HasIndex("URLId");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("URLShortenerApp.Data.Models.URL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("URL identifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("URL creation date");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Original URL");

                    b.Property<string>("SecretUrl")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Secret URL");

                    b.Property<string>("ShortenedUrl")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("Shortened URL");

                    b.HasKey("Id");

                    b.HasIndex("SecretUrl")
                        .IsUnique();

                    b.ToTable("URLs");
                });

            modelBuilder.Entity("URLShortenerApp.Data.Models.Record", b =>
                {
                    b.HasOne("URLShortenerApp.Data.Models.URL", "URL")
                        .WithMany("Records")
                        .HasForeignKey("URLId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("URL");
                });

            modelBuilder.Entity("URLShortenerApp.Data.Models.URL", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
