// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URLShortenerApp.Data;

#nullable disable

namespace URLShortenerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250702124048_DatabaseSeeding")]
    partial class DatabaseSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URLShortenerApp.Data.Models.Record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Record identifier");

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime2")
                        .HasComment("URL access date");

                    b.Property<Guid>("URLId")
                        .HasColumnType("uniqueidentifier")
                        .HasComment("URL record identifier");

                    b.Property<string>("UserIPAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasComment("User IP adress");

                    b.HasKey("Id");

                    b.HasIndex("URLId");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86739286-18d5-4f31-85b6-f6d824108650"),
                            AccessDate = new DateTime(2025, 7, 2, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(4947),
                            URLId = new Guid("e244bc69-5e82-4cdc-aabf-69a7c620d282"),
                            UserIPAddress = "165.122.32.209"
                        },
                        new
                        {
                            Id = new Guid("e2723ab2-6c56-43e4-b594-a59f9a3b9006"),
                            AccessDate = new DateTime(2025, 6, 22, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5654),
                            URLId = new Guid("e244bc69-5e82-4cdc-aabf-69a7c620d282"),
                            UserIPAddress = "165.122.32.209"
                        },
                        new
                        {
                            Id = new Guid("8b91667d-031a-4c26-8817-a4c05fbca351"),
                            AccessDate = new DateTime(2025, 6, 29, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5656),
                            URLId = new Guid("e244bc69-5e82-4cdc-aabf-69a7c620d282"),
                            UserIPAddress = "119.240.93.167"
                        },
                        new
                        {
                            Id = new Guid("149c2f2c-14ec-4169-bb66-7e8c014c78ac"),
                            AccessDate = new DateTime(2025, 7, 1, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5657),
                            URLId = new Guid("e244bc69-5e82-4cdc-aabf-69a7c620d282"),
                            UserIPAddress = "165.122.32.209"
                        },
                        new
                        {
                            Id = new Guid("37898beb-b7b7-4398-ab01-96596bedee10"),
                            AccessDate = new DateTime(2025, 6, 23, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5658),
                            URLId = new Guid("e244bc69-5e82-4cdc-aabf-69a7c620d282"),
                            UserIPAddress = "1.225.63.20"
                        },
                        new
                        {
                            Id = new Guid("8f55796e-b0dd-451e-a22e-8335af736b6d"),
                            AccessDate = new DateTime(2025, 6, 17, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5662),
                            URLId = new Guid("f2fd801f-6493-4a93-a9fa-1829c8ac21fd"),
                            UserIPAddress = "215.148.253.91"
                        },
                        new
                        {
                            Id = new Guid("1f034183-ec79-4ea2-a0c1-8bd47967efff"),
                            AccessDate = new DateTime(2025, 6, 25, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5663),
                            URLId = new Guid("f2fd801f-6493-4a93-a9fa-1829c8ac21fd"),
                            UserIPAddress = "165.122.32.209"
                        },
                        new
                        {
                            Id = new Guid("d1c80305-ec15-4a89-b96a-b8a4dd259959"),
                            AccessDate = new DateTime(2025, 6, 30, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5663),
                            URLId = new Guid("f2fd801f-6493-4a93-a9fa-1829c8ac21fd"),
                            UserIPAddress = "165.218.50.241"
                        },
                        new
                        {
                            Id = new Guid("8f602fd7-869a-484a-9cf2-6f41d4dacbad"),
                            AccessDate = new DateTime(2025, 7, 1, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5664),
                            URLId = new Guid("f2fd801f-6493-4a93-a9fa-1829c8ac21fd"),
                            UserIPAddress = "215.148.253.91"
                        },
                        new
                        {
                            Id = new Guid("e13642b1-c894-41d3-acc9-8211e8a2ba8b"),
                            AccessDate = new DateTime(2025, 6, 12, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5667),
                            URLId = new Guid("19cbaea2-e65e-4931-8c25-685708d7f4c8"),
                            UserIPAddress = "119.240.93.167"
                        },
                        new
                        {
                            Id = new Guid("fad2151d-5e15-4b6c-9db3-fd9149217e7e"),
                            AccessDate = new DateTime(2025, 6, 7, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5668),
                            URLId = new Guid("19cbaea2-e65e-4931-8c25-685708d7f4c8"),
                            UserIPAddress = "165.218.50.241"
                        },
                        new
                        {
                            Id = new Guid("1eaa56a1-99c6-4c5c-8351-58f03a381c47"),
                            AccessDate = new DateTime(2025, 6, 27, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5669),
                            URLId = new Guid("19cbaea2-e65e-4931-8c25-685708d7f4c8"),
                            UserIPAddress = "128.181.26.173"
                        },
                        new
                        {
                            Id = new Guid("6051d816-2a0c-439f-90ac-cba5b7d913df"),
                            AccessDate = new DateTime(2025, 7, 1, 12, 40, 48, 458, DateTimeKind.Utc).AddTicks(5670),
                            URLId = new Guid("19cbaea2-e65e-4931-8c25-685708d7f4c8"),
                            UserIPAddress = "165.122.32.209"
                        });
                });

            modelBuilder.Entity("URLShortenerApp.Data.Models.URL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("URL identifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasComment("URL creation date");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasComment("Original URL");

                    b.Property<string>("SecretUrl")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasComment("Secret URL");

                    b.Property<string>("ShortenedUrl")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasComment("Shortened URL");

                    b.HasKey("Id");

                    b.HasIndex("SecretUrl")
                        .IsUnique();

                    b.ToTable("URLs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e244bc69-5e82-4cdc-aabf-69a7c620d282"),
                            CreationDate = new DateTime(2025, 6, 7, 12, 40, 48, 457, DateTimeKind.Utc).AddTicks(9413),
                            OriginalUrl = "https://www.progress.com/",
                            SecretUrl = "NlptN4Bw1P",
                            ShortenedUrl = "2af135"
                        },
                        new
                        {
                            Id = new Guid("f2fd801f-6493-4a93-a9fa-1829c8ac21fd"),
                            CreationDate = new DateTime(2025, 6, 2, 12, 40, 48, 457, DateTimeKind.Utc).AddTicks(9825),
                            OriginalUrl = "https://www.dev.bg/",
                            SecretUrl = "BtGWzHZ96t",
                            ShortenedUrl = "9329e2"
                        },
                        new
                        {
                            Id = new Guid("19cbaea2-e65e-4931-8c25-685708d7f4c8"),
                            CreationDate = new DateTime(2025, 5, 28, 12, 40, 48, 457, DateTimeKind.Utc).AddTicks(9831),
                            OriginalUrl = "https://www.telerik.com/",
                            SecretUrl = "X9k2v3Q8yF",
                            ShortenedUrl = "9c13ca"
                        });
                });

            modelBuilder.Entity("URLShortenerApp.Data.Models.Record", b =>
                {
                    b.HasOne("URLShortenerApp.Data.Models.URL", "URL")
                        .WithMany("Records")
                        .HasForeignKey("URLId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("URL");
                });

            modelBuilder.Entity("URLShortenerApp.Data.Models.URL", b =>
                {
                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
